spring.application.name=SpringBootRestfulWebServices

spring.datasource.url=jdbc:mysql://localhost:3306/restfuldb
spring.datasource.username=root
spring.datasource.password=hemant@85
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
